/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.agente;

import br.com.monitoringcontrol.Bean.Clientes;
import br.com.monitoringcontrol.Bean.Coordenador;
import br.com.monitoringcontrol.Dao.ServiceDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardWatchEventKinds;
import java.nio.file.WatchEvent;
import java.nio.file.WatchKey;
import java.nio.file.WatchService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;
import com.jcraft.jsch.*;
import java.io.InputStream;


/**
 *
 * @author noslineda
 */
public class jFrameMonitorControl extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMonitorControl
     */
    public String nomeSelecionado="";
    public String filtro ="";
    private String porta="";
    static public boolean status_agente ;
    public List<Clientes> clientes;
    public String servidorSelected = "";

    public jFrameMonitorControl() {
        initComponents();
        status_agente = isAgenteRodando();
        System.out.println("Status_agente: "+status_agente);
        textScroll.setSelected(true);
        if(status_agente){
            status_agente = false;
            jBAgente.setText("Ativo");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.blue); 
            //executarShellScript("/home/nuc/Documentos/agente.sh");
            
        }else{
            status_agente =true;
            jBAgente.setText("Desativado");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.red);
            jTbusca.setText("");
            //finalizarAgente();
        }
        setIconImage(new ImageIcon(getClass().getResource("/img/icon_fairtek.png")).getImage());
        try {
            
            
            status_agente = isAgenteRodando();
            
            //System.out.println("jFrameMonitorControl: "+status_agente);
            //Icon logotipo = new ImageIcon("img/fairtek-logo.png");
            //logo.setIcon(logotipo);
           // Icon searchIcon = new ImageIcon("img/lupa.png");
            //File file = new File("img/lupa2.png");
            //busca.setIcon(searchIcon); // ou busca.setIcon(search);
            Icon logotipo = new ImageIcon(getClass().getResource("/img/fairtek-logo.png"));
            logo.setIcon(logotipo);

            Icon searchIcon = new ImageIcon(getClass().getResource("/img/lupa2.png"));
            busca.setIcon(searchIcon);

            Icon searchIcon2 = new ImageIcon(getClass().getResource("/img/lupa2.png"));
        } catch (Exception e) {
            //System.out.println("Erro ao carregar o ícone: " + e.getMessage());
        }
        //jBAgente.setBackground(Color.red);
        select_porta.setModel(new javax.swing.DefaultComboBoxModel<>(buscarPortasDoBanco()));
        select_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_portaActionPerformed(evt);
            }
            
        });
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Path caminhoArquivo = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
                jFrameMonitorControl jfmc = new jFrameMonitorControl();
                //jfmc.setVisible(true);
                carregarLog(caminhoArquivo, jfmc.textLog);
                new Thread(() -> monitorarArquivo(caminhoArquivo, jfmc.textLog)).start();
            }
        });*/
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBAgente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        select_porta = new javax.swing.JComboBox<>();
        jTbusca = new javax.swing.JTextField();
        busca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sizeFont = new javax.swing.JSpinner();
        textScroll = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 5));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        logo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                logoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Agente");

        jBAgente.setText("Desativado");
        jBAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        select_porta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        select_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_portaActionPerformed(evt);
            }
        });

        jTbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Filtros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(select_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Ajustes");

        jLabel3.setText("Font:");

        sizeFont.setValue(12);
        sizeFont.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sizeFontAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                sizeFontAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sizeFont.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeFontStateChanged(evt);
            }
        });

        textScroll.setText("Scroll");
        textScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textScrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(textScroll)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textScroll)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTabbedPane1HierarchyChanged(evt);
            }
        });

        textLog.setColumns(20);
        textLog.setRows(5);
        textLog.setTabSize(12);
        jScrollPane1.setViewportView(textLog);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 909, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:

        //ImageIcon searchIcon = new ImageIcon("fairtek-logo.png");
        //Image img = searchIcon.getImage().getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
        //Image newImg = img.getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH); // ajuste o tamanho desejado
        //Icon search = new ImageIcon(newImg);
        //busca.setIcon(search);

    }//GEN-LAST:event_jPanel2AncestorAdded

    private void textScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textScrollActionPerformed
        // TODO add your handling code here:
        System.out.println("TextScroll: "+ textScroll.isSelected());
    }//GEN-LAST:event_textScrollActionPerformed

    private void sizeFontStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeFontStateChanged
        // Obtém o valor do controle (por exemplo, um JSpinner ou JSlider)
        int fontSize = (int) sizeFont.getValue();

        // Cria uma nova fonte com o tamanho desejado, mantendo o nome e estilo atuais
        textLog.setFont(textLog.getFont().deriveFont((float) fontSize));
        //Path caminhoArquivo = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");

        //carregarLog(caminhoArquivo, textLog, filtro);
        //System.out.println("font size: " + fontSize);
    }//GEN-LAST:event_sizeFontStateChanged

    private void sizeFontAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sizeFontAncestorMoved
        // TODO add your handling code here:
        // System.out.println(sizeFont.getValue());
    }//GEN-LAST:event_sizeFontAncestorMoved

    private void sizeFontAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sizeFontAncestorAdded
        // TODO add your handling code here:

        //System.out.println(sizeFont.getValue());
    }//GEN-LAST:event_sizeFontAncestorAdded

    private void jTbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscaActionPerformed
        // TODO add your handling code here:
        this.filtro = jTbusca.getText();
        select_porta.setSelectedItem("Selecione a porta");
        //Path caminhoArquivo = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
        //Path caminhoArquivo = Paths.get("Agente.log");
        String portaSelecionada = (String) select_porta.getSelectedItem();
        carregarLog(caminhoArquivo, textLog, jScrollPane1, portaSelecionada,jTbusca,isAgenteRodando(),textScroll, this.servidorSelected);

    }//GEN-LAST:event_jTbuscaActionPerformed

    private void select_portaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_portaActionPerformed
        // TODO add your handling code here:
        this.nomeSelecionado = (String) select_porta.getSelectedItem();
        //Path caminhoArquivo = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
        String portaSelecionada = (String) select_porta.getSelectedItem();
        if(this.nomeSelecionado  == "Selecione a porta"){

            carregarLog(caminhoArquivo, textLog,jScrollPane1, portaSelecionada,jTbusca,isAgenteRodando(),textScroll,this.servidorSelected);
        }else{
            carregarLog(caminhoArquivo, textLog,jScrollPane1, portaSelecionada,jTbusca,isAgenteRodando(),textScroll,this.servidorSelected);
        }
    }//GEN-LAST:event_select_portaActionPerformed

    private void jBAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgenteActionPerformed
        // TODO add your handling code here:
        // System.out.println(status_agente);
        //status_agente= true?false:true;
        //System.out.println(status_agente);
        if(status_agente){
            status_agente = false;
            //System.out.println("Desativado "+status_agente);
            jBAgente.setText("Ativo");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.blue);
            executarShellScript("/home/nuc/Documentos/agente.sh");

        }else{
            status_agente =true;
            jBAgente.setText("Desativado");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.red);
            jTbusca.setText("");
            finalizarAgente();

            // System.out.println("Ativo "+status_agente);

        }

        //System.out.println(jBAgente.getText());
    }//GEN-LAST:event_jBAgenteActionPerformed

    private void logoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_logoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_logoAncestorAdded

    private void jTabbedPane1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTabbedPane1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1HierarchyChanged

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(jFrameMonitorControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Path caminhoArquivo = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
                Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
                jFrameMonitorControl jfmc = new jFrameMonitorControl();
                jfmc.setVisible(true);
                ServiceDao dao = null;
                try {
                    dao = new ServiceDao();
                } catch (Exception ex) {
                    Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    List<Clientes> servidores = dao.buscarTodosClientes();
                    jfmc.criarAbasParaServidores(servidores);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                String portaSelecionada = (String) jfmc.select_porta.getSelectedItem();
                carregarLog(caminhoArquivo, jfmc.textLog, jfmc.jScrollPane1,
                        portaSelecionada, jfmc.jTbusca, jfmc.isAgenteRodando(), jfmc.textScroll, jfmc.servidorSelected);
                new Thread(() -> monitorarArquivo(caminhoArquivo, jfmc.textLog, jfmc.jScrollPane1,
                jfmc.select_porta, jfmc.jTbusca, jfmc.isAgenteRodando(), jfmc.textScroll, jfmc.servidorSelected)).start();
            }
        });
    }
    
    private String[] buscarPortasDoBanco() {
        this.buscarClientes();
        
        try {
           
            ServiceDao dao = new ServiceDao();
            List<Coordenador> coordenadores = dao.buscarTodosCoordenadores();
            String[] nomes = new String[coordenadores.size() + 1];
            nomes[0] = "Selecione a porta"; // Definir a primeira posição
        
            // Preencher o restante do array com os nomes vindos do banco
            for (int i = 0; i < coordenadores.size(); i++) {
                nomes[i + 1] = coordenadores.get(i).getNome();
            }

            
            return nomes;
        } catch (Exception ex) {
            Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, ex);
            return new String[] { "Erro ao carregar" };
        }
    }
    private List<Clientes> buscarClientes(){
        try {
            ServiceDao dao = new ServiceDao();
            this.clientes = dao.buscarTodosClientes(); // já retorna List<Clientes>
        } catch (Exception ex) {
            Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Lista de clientes: " + clientes);
        return clientes;
    }
    // Supondo que você já tenha o jTabbedPane1 declarado
    private void criarAbasParaServidores(List<Clientes> servidores) {
        for (Clientes servidor : servidores) {
            System.out.println("###########Servidores: " + servidor.getNome());
            JTextArea textLog = new JTextArea();
            textLog.setEditable(false);
            JScrollPane scrollPane = new JScrollPane(textLog);
            //scrollPane.setPreferredSize(new Dimension(0, 0));
            jTabbedPane1.addTab("Servidor: " + servidor.getNome(), scrollPane);
        }
        //this.setLayout(new BorderLayout());
        //this.add(jTabbedPane1, BorderLayout.CENTER);
        jTabbedPane1.addChangeListener(e -> {
            int index = jTabbedPane1.getSelectedIndex();
            String titulo = jTabbedPane1.getTitleAt(index);
            Component comp = jTabbedPane1.getSelectedComponent();
            if (comp instanceof JScrollPane) {
                JScrollPane scroll = (JScrollPane) comp;
                JViewport viewport = scroll.getViewport();
                Component view = viewport.getView();
                if (view instanceof JTextArea) {
                    JTextArea textArea = (JTextArea) view;
                    System.out.println("Aba selecionada: " + titulo);
                    this.servidorSelected = titulo;
                    if (this.servidorSelected == null) {
                        Path caminho = Paths.get("/home/nuc/Agente/Agente.log");
                        String portaSelecionada = (String) select_porta.getSelectedItem();
                        carregarLog(caminho, textLog, jScrollPane1,
              portaSelecionada, jTbusca, isAgenteRodando(), textScroll, this.servidorSelected);
                    } else {
                        // Exemplo: acessar arquivo remoto via SSH
                        //acessarArquivoRemoto(this.servidorSelected, "/home/nuc/Agente/Agente.log");
                    }

                    Path caminho = Paths.get("/home/nuc/Agente/Agente.log");
                    String portaSelecionada = (String) select_porta.getSelectedItem();
                    carregarLog(caminho, textLog, jScrollPane1,
                        portaSelecionada, jTbusca, isAgenteRodando(), textScroll, this.servidorSelected);
                    
                }
            }
        });

    }

    private static void carregarLog(Path caminhoArquivo, JTextArea textArea, JScrollPane scrollPane, String select_porta, JTextField campoBusca, boolean ativado, JRadioButton textScroll, String server) {
        SwingUtilities.invokeLater(() -> {
            try {
                if (textArea.getSelectionStart() != textArea.getSelectionEnd()) {
                    return;
                }
                int scrollValue = scrollPane.getVerticalScrollBar().getValue();
                List<String> linhas = Files.readAllLines(caminhoArquivo, StandardCharsets.UTF_8);
                StringBuilder sb = new StringBuilder();
                String busca = campoBusca.getText();
                for (String linha : linhas) {
                    if (busca == null || busca.isEmpty() || linha.toLowerCase().contains(busca.toLowerCase())) {
                        if (server == null || server.isEmpty()) {
                            sb.append("Servidor Principal " + " - " + linha).append("\n");
                        }else{
                            sb.append("Servidor " + server + " - " + linha).append("\n");
                        } 
                    }
                }
                textArea.setText(sb.toString());
                if (!textScroll.isSelected()) {
                    scrollPane.getVerticalScrollBar().setValue(scrollValue);
                    int start = textArea.viewToModel(scrollPane.getViewport().getViewPosition());
                    textArea.setCaretPosition(start);
                } else {
                    textArea.setCaretPosition(textArea.getDocument().getLength());
                }
            } catch (IOException e) {
                textArea.setText("Erro ao carregar o log: " + e.getMessage());
            }
        });
    }

    



    private static void monitorarArquivo(Path caminhoArquivo, JTextArea textArea,JScrollPane scrollPane, JComboBox<String> select_porta, JTextField campoBusca, boolean ativado,JRadioButton textScroll,String server) {
       
        status_agente = isAgenteRodando();
        
        try (WatchService watchService = FileSystems.getDefault().newWatchService()) {
            //Path caminho = Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
            Path caminho = Paths.get("/home/nuc/Agente/Agente.log");
            Path parent = caminhoArquivo.getParent();
            if (parent == null) parent = Paths.get("."); 
            parent.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY);
            while (true) {
                WatchKey key = watchService.take();
                for (WatchEvent<?> event : key.pollEvents()) {
                    if (event.context().toString().equals(caminhoArquivo.getFileName().toString())) {
                    // Sempre pega o valor atual da porta e do campo de busca
                    String portaSelecionada = (String) select_porta.getSelectedItem();
                    String filtroBusca = campoBusca.getText();
                    carregarLog(caminhoArquivo, textArea, scrollPane,  portaSelecionada, campoBusca, status_agente, textScroll, server);
                }
                }
                key.reset();
            }
        } catch (IOException | InterruptedException e) {
            SwingUtilities.invokeLater(() -> textArea.setText("Erro ao monitorar o arquivo: " + e.getMessage()));
        }
    }
    public static boolean isAgenteRodando() {
        try {
            String os = System.getProperty("os.name").toLowerCase();
            Process processo;
            if (os.contains("win")) {
                processo = Runtime.getRuntime().exec("tasklist /FI \"IMAGENAME eq java.exe\"");
            } else {
                // Usa pgrep para buscar processos Java rodando Agente.jar
                String[] cmd = {"/bin/sh", "-c", "ps aux | grep '[A]gente.jar'"};
                processo = Runtime.getRuntime().exec(cmd);
            }
            BufferedReader leitor = new BufferedReader(new InputStreamReader(processo.getInputStream()));
            String linha;
            while ((linha = leitor.readLine()) != null) {
                // Garante que não é a própria linha do grep
                if (linha.toLowerCase().contains("agente.jar") && !linha.toLowerCase().contains("grep")) {
                    return true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
    public static void executarShellScript(String caminhoScript) {
        //System.out.println("Caminho do agente.sh: " + caminhoScript);
        try {
            ProcessBuilder pb = new ProcessBuilder("bash", caminhoScript);
            pb.redirectErrorStream(true);
            Process process = pb.start();

            // Leia a saída para evitar travamento por buffer cheio
            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(process.getInputStream()))) {
                        String linha;
                    while ((linha = reader.readLine()) != null) {
                        //System.out.println(linha);
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();

            // Não espere o término se o script roda em background
            // int exitCode = process.waitFor();
            // System.out.println("Script finalizado com código: " + exitCode);
            //System.out.println("Script iniciado.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void finalizarAgente() {
        try {
            // Encontra o PID do Agente.jar e finaliza com kill -9
            String[] cmd = {
                "/bin/sh",
                "-c",
                "sudo ps aux | grep '[A]gente.jar' | awk '{print $2}' | xargs -r sudo kill -9",
                
            };
            Process process = Runtime.getRuntime().exec(cmd);
            process.waitFor();
            //System.out.println("Agente.jar finalizado (se estava em execução).");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busca;
    private javax.swing.JButton jBAgente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTbusca;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> select_porta;
    private javax.swing.JSpinner sizeFont;
    private javax.swing.JTextArea textLog;
    private javax.swing.JRadioButton textScroll;
    // End of variables declaration//GEN-END:variables
}
