/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.agente;

import br.com.monitoringcontrol.Bean.Clientes;
import br.com.monitoringcontrol.Bean.Coordenador;
import br.com.monitoringcontrol.Bean.SSHLogReader;
import br.com.monitoringcontrol.Dao.ServiceDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardWatchEventKinds;
import java.nio.file.WatchEvent;
import java.nio.file.WatchKey;
import java.nio.file.WatchService;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;
import com.jcraft.jsch.*;
import java.io.InputStream;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JTabbedPane;
import java.io.File;
import java.io.RandomAccessFile;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.UIManager;

/**
 *
 * @author noslineda
 */
public class jFrameMonitorControl extends javax.swing.JFrame {

    /**
     * Creates new form jFrameMonitorControl
     */
    public String nomeSelecionado = "";
    public String filtro = "";
    private String porta = "";
    static public boolean status_agente;
    public List<Clientes> clientes;
    public String servidorSelected = "";
    private Set<Integer> abasAtivas = new HashSet<>();
    private volatile int abaAtivaMonitorada = -1;
    private static FileLock lock;

    public jFrameMonitorControl() {
        initComponents();
        status_agente = isAgenteRodando();
        System.out.println("Status_agente: " + status_agente);

        if (status_agente) {
            status_agente = false;
            jBAgente.setText("Ativo");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.blue);
            
            // executarShellScript("/home/nuc/Documentos/agente.sh");
        } else {
            status_agente = true;
            jBAgente.setText("Desativado");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.red);
            jTbusca.setText("");
            // finalizarAgente();
        }
        setIconImage(new ImageIcon(getClass().getResource("/img/icon_fairtek.png")).getImage());
        try {
            status_agente = isAgenteRodando();
            Icon logotipo = new ImageIcon(getClass().getResource("/img/fairtek-logo.png"));
            logo.setIcon(logotipo);
        } catch (Exception e) {
            System.out.println("Erro ao carregar o ícone: " + e.getMessage());
        }
        // jBAgente.setBackground(Color.red);
        select_porta.setModel(new javax.swing.DefaultComboBoxModel<>(buscarPortasDoBanco()));
        this.buscarClientes();
        this.preencherClientesNoPanel();
        select_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_portaActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jBAgente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        select_porta = new javax.swing.JComboBox<>();
        jTbusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sizeFont = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 5));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        logo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                logoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Status Agente Principal");

        jBAgente.setText("Desativado");
        jBAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        select_porta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        select_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_portaActionPerformed(evt);
            }
        });

        jTbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Filtros");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(select_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(select_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Ajustes");

        jLabel3.setText("Font:");

        sizeFont.setValue(12);
        sizeFont.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sizeFontAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                sizeFontAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sizeFont.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeFontStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sizeFont, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTabbedPane1HierarchyChanged(evt);
            }
        });

        jMenu1.setText("Ferramentas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("MudaIp");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1502, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Servidor Pricipal");
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTabbedPane1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1HierarchyChanged

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanel2AncestorAdded

    private void sizeFontStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_sizeFontStateChanged
        // Obtém o valor do controle (por exemplo, um JSpinner ou JSlider)
        int fontSize = (int) sizeFont.getValue();
        // Cria uma nova fonte com o tamanho desejado, mantendo o nome e estilo atuais
        //textLog.setFont(textLog.getFont().deriveFont((float) fontSize));
        // Path caminhoArquivo =
        // Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
        // carregarLog(caminhoArquivo, textLog, filtro);
    }// GEN-LAST:event_sizeFontStateChanged

    private void sizeFontAncestorMoved(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_sizeFontAncestorMoved
        // TODO add your handling code here:
    }// GEN-LAST:event_sizeFontAncestorMoved

    private void sizeFontAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_sizeFontAncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_sizeFontAncestorAdded

    private void jTbuscaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTbuscaActionPerformed
        // TODO add your handling code here:
        this.filtro = jTbusca.getText();
        select_porta.setSelectedItem("Selecione a porta");
        // Path caminhoArquivo =
        // Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
        // Path caminhoArquivo = Paths.get("Agente.log");
        String portaSelecionada = (String) select_porta.getSelectedItem();
        //carregarLog(caminhoArquivo, textLog, jScrollPane1, portaSelecionada, jTbusca, isAgenteRodando());

    }// GEN-LAST:event_jTbuscaActionPerformed

    private void select_portaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_select_portaActionPerformed
        // TODO add your handling code here:
        this.nomeSelecionado = (String) select_porta.getSelectedItem();
        // Path caminhoArquivo =
        // Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
        String portaSelecionada = (String) select_porta.getSelectedItem();
        if (this.nomeSelecionado == "Selecione a porta") {
           // carregarLog(caminhoArquivo, textLog, jScrollPane1, portaSelecionada, jTbusca, isAgenteRodando());
        } else {
            //carregarLog(caminhoArquivo, textLog, jScrollPane1, portaSelecionada, jTbusca, isAgenteRodando());
        }
    }// GEN-LAST:event_select_portaActionPerformed

    private void jBAgenteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAgenteActionPerformed
        System.out.println("Status_agente: " + status_agente);
        if (status_agente) {
            status_agente = false;
            jBAgente.setText("Ativo");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.blue);
            executarShellScript("/home/nuc/Documentos/agente.sh");
            System.out.println("Ativa o Agente");

        } else {
            status_agente = true;
            jBAgente.setText("Desativado");
            jBAgente.setForeground(Color.white);
            jBAgente.setBackground(Color.red);
            jTbusca.setText("");
            finalizarAgente();
            System.out.println("Finaliza Agente");
        }

        System.out.println(jBAgente.getText());
    }// GEN-LAST:event_jBAgenteActionPerformed

    private void logoAncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_logoAncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_logoAncestorAdded

    //private void jTabbedPane1HierarchyChanged(java.awt.event.HierarchyEvent evt) {// GEN-FIRST:event_jTabbedPane1HierarchyChanged
        // TODO add your handling code here:
    //}// GEN-LAST:event_jTabbedPane1HierarchyChanged

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_jPanel5AncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            // Caminho absoluto do script
            String script = "/home/nuc/Documentos/mudaIp.sh";
            // Abre o terminal e executa o script
            new ProcessBuilder("gnome-terminal", "--", "bash", "-c", script + "; exec bash").start();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao executar script: " + ex.getMessage());
        }
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        if (!obterLogUnico()) {
            System.out.println("O programa já está em execução.");
            System.exit(1);
        }
        configurarLookAndFeel();
        java.awt.EventQueue.invokeLater(() -> {
            try {
                iniciarAplicacao();
            } catch (Exception e) {
                Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, e);
            }
        });
    }

    private static boolean obterLogUnico() {
        try {
            File file = new File(System.getProperty("java.io.tmpdir"), "monitorLog.lock");
            FileChannel channel = new RandomAccessFile(file, "rw").getChannel();
            lock = channel.tryLock();
            return lock != null;
        } catch (Exception e) {
            Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, e);
            return false;
        }
    }

    private static void configurarLookAndFeel() {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private static void iniciarAplicacao() throws Exception {
        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
        jFrameMonitorControl jfmc = new jFrameMonitorControl();
        jfmc.setVisible(true);
        ServiceDao dao = new ServiceDao();
        jfmc.criarAbasParaServidores();
        String portaSelecionada = (String) jfmc.select_porta.getSelectedItem();
        //carregarLog(caminhoArquivo, jfmc.textLog, jfmc.jScrollPane1,portaSelecionada, jfmc.jTbusca, jfmc.isAgenteRodando());
        //new Thread(() -> monitorarArquivo(caminhoArquivo, jfmc.textLog, jfmc.jScrollPane1,jfmc.select_porta, jfmc.jTbusca, jfmc.isAgenteRodando())).start();
    }

    private void preencherClientesNoPanel() {
        try {
            jPanel5.removeAll();
            jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
            ServiceDao dao = new ServiceDao();
            List<Clientes> clientes = dao.buscarTodosServidores();
            JButton btn = new JButton();
                
            String titulo ="";
            for (Clientes c : clientes) {
                if(c.getPrincipal()==1){
                    titulo = "Servidor Principal \n";
                     btn = new JButton(titulo);
                }else{
                    titulo =c.getNome();
                    btn = new JButton(titulo + " - " + c.getIp());
                }
                
                btn.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
                btn.setForeground(java.awt.Color.WHITE);
                btn.setBackground(new java.awt.Color(0, 102, 204));
                btn.addActionListener(e -> {
                    try {
                        //String comando = "sshpass -p fairtek2018 ssh -p 22 nuc@" + c.getIp() + " 'cd /home/nuc/Agente && tail -f Agente.log'";
                        if(c.getPrincipal()==1){
                            String comando = "cd /home/nuc/Agente && tail -f Agente.log";

                            new ProcessBuilder("gnome-terminal", "--", "bash", "-c", comando + "; exec bash").start();
                        }else{
                            String comando = "sshpass -p fairtek2018 ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null nuc@" 
                                + c.getIp() 
                                + " 'cd /home/nuc/Agente && tail -f Agente.log'";

                            new ProcessBuilder("gnome-terminal", "--", "bash", "-c", comando + "; exec bash").start();
                        }
                        
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao executar SSH: " + ex.getMessage());
                    }
                });
                jPanel5.add(btn);
                jPanel5.add(Box.createVerticalStrut(8));
            }
            jPanel5.revalidate();
            jPanel5.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar clientes: " + ex.getMessage());
        }
    }

    private String[] buscarPortasDoBanco() {
        String[] nomes = new String[22];
        nomes[0] = "Selecione a porta";
        nomes[1] = "/dev/ttyUSB0";
        nomes[2] = "/dev/ttyUSB1";
        nomes[3] = "/dev/ttyUSB2";
        nomes[4] = "/dev/ttyUSB3";
        nomes[5] = "/dev/ttyUSB4";
        nomes[6] = "/dev/ttyUSB5";
        nomes[7] = "/dev/ttyUSB6";
        nomes[8] = "/dev/ttyUSB7";
        nomes[9] = "/dev/ttyUSB8";
        nomes[10] = "/dev/ttyUSB9";
        nomes[11] = "/dev/ttyUSB10";
        nomes[12] = "/dev/ttyUSB11";
        nomes[13] = "/dev/ttyUSB12";
        nomes[14] = "/dev/ttyUSB13";
        nomes[15] = "/dev/ttyUSB14";
        nomes[16] = "/dev/ttyUSB15";
        nomes[17] = "/dev/ttyUSB16";
        nomes[18] = "/dev/ttyUSB17";
        nomes[19] = "/dev/ttyUSB18";
        nomes[20] = "/dev/ttyUSB19";
        nomes[21] = "/dev/ttyUSB20";
        return nomes;
    }

    private List<Clientes> buscarClientes() {
        try {
            ServiceDao dao = new ServiceDao();
            this.clientes = dao.buscarTodosServidores(); // já retorna List<Clientes>
        } catch (Exception ex) {
            Logger.getLogger(jFrameMonitorControl.class.getName()).log(Level.SEVERE, null, ex);
        }
        return clientes;
    }

    private void criarAbasParaServidores() {
        List<Clientes> servidores = buscarClientes();
        int offset = jTabbedPane1.getTabCount();
        for (Clientes servidor : servidores) {
            JTextArea textLog = new JTextArea("Aguardando seleção...");
            textLog.setEditable(false);

            // Faz o JTextArea expandir corretamente
            textLog.setLineWrap(true);
            textLog.setWrapStyleWord(true);

            JScrollPane scrollPane = new JScrollPane(textLog,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

            // Garante que o scrollPane ocupe todo o espaço da aba
            scrollPane.setPreferredSize(new Dimension(400, 300));
            scrollPane.setMinimumSize(new Dimension(200, 150));
            if(servidor.getPrincipal() == 1){
                jTabbedPane1.addTab("Servidor Principal: " + servidor.getNome(), scrollPane);
            }else{
                jTabbedPane1.addTab("Servidor: " + servidor.getNome(), scrollPane);
            }
        }
        // Listener para seleção de abas
        jTabbedPane1.addChangeListener(e -> {
            int index = jTabbedPane1.getSelectedIndex();
            if (index >= offset) {
                Clientes servidorSelecionado = servidores.get(index - offset);
                JScrollPane scroll = (JScrollPane) jTabbedPane1.getComponentAt(index);
                JTextArea textArea = (JTextArea) scroll.getViewport().getView();
                iniciarMonitoramentoSsh(servidorSelecionado, textArea);
            }
        });
    }


    private void iniciarMonitoramentoSsh(Clientes servidor, JTextArea targetTextArea) {
        int indexAtual = jTabbedPane1.getSelectedIndex();
        // Define que APENAS esta aba deve rodar a partir de agora
        abaAtivaMonitorada = indexAtual;
        new Thread(() -> {
            SSHLogReader r = new SSHLogReader();
            String portaSelecionada = (String) select_porta.getSelectedItem();
            try {
                // O loop só executa se esta thread ainda pertencer à aba ativa
                while (abaAtivaMonitorada == indexAtual) {
                    int fontSize = (int) sizeFont.getValue();
                    String texto = this.jTbusca.getText();
                    String logConteudo="";
                    StringBuilder filtrado = new StringBuilder();
                    String titulo ="";
                    if (servidor.getPrincipal() == 1) {
                        titulo = "Servidor Principal";
                        Path caminhoArquivo = Paths.get("/home/nuc/Agente/Agente.log");
                        List<String> linhas = Files.readAllLines(caminhoArquivo, StandardCharsets.UTF_8);
                        logConteudo = String.join("\n", linhas);
                         //System.out.println(logConteudo);
                    } else {
                        titulo = "Servidor:";
                        logConteudo = r.lerUltimasLinhas(
                    "nuc", "fairtek2018", servidor.getIp(), "/home/nuc/Agente/Agente.log"
                        );
                    }
                    for (String linha : logConteudo.split("\n")) {
                        boolean portaOk = this.nomeSelecionado.equals("Selecione a porta") || linha.contains(this.nomeSelecionado);
                        boolean textoOk = texto.isEmpty() || linha.toLowerCase().contains(texto.toLowerCase());

                        if (portaOk && textoOk) {
                            filtrado.append(titulo)
                            .append(" ")
                            .append(servidor.getNome())
                            .append(" - ")
                            .append(linha)
                            .append("\n");
                        }
                    }
                    
                    // Verifica novamente antes de atualizar a interface gráfica
                    if (abaAtivaMonitorada != indexAtual) {
                        break;
                    }
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        targetTextArea.setText(filtrado.toString());
                        targetTextArea.setFont(targetTextArea.getFont().deriveFont((float) fontSize));
                        targetTextArea.setCaretPosition(targetTextArea.getDocument().getLength());
                    });

                    Thread.sleep(500);
                }
            } catch (InterruptedException e) {
                // Thread interrompida normalmente
            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    targetTextArea.setText("Erro na conexão dinâmica: " + e.getMessage());
                });
            }
            System.out.println("Thread da aba " + indexAtual + " encerrada.");
        }).start();
    }
    private static void carregarLog(Path caminhoArquivo, JTextArea textArea, JScrollPane scrollPane,
        String select_porta, JTextField campoBusca, boolean ativado) {
        SwingUtilities.invokeLater(() -> {
            try {
                if (textArea.getSelectionStart() != textArea.getSelectionEnd()) {
                    return;
                }
                // Capture o valor do scroll antes de limpar o texto
                int scrollValue = scrollPane.getVerticalScrollBar().getValue();
                String busca = campoBusca.getText().toLowerCase();
                // String portaSelecionada = select_porta.getSelectedItem().toString(); //
                // Pegando o texto do combo
                StringBuilder sb = new StringBuilder();
                // Usar Files.lines é mais eficiente que readAllLines para arquivos grandes
                List<String> linhas = Files.readAllLines(caminhoArquivo, StandardCharsets.UTF_8);

                for (String linha : linhas) {
                    // Lógica de Filtro Consolidada
                    boolean filtroPorta = select_porta.equals("Selecione a porta") || linha.contains(select_porta);
                    boolean filtroBusca = busca.isEmpty() || linha.toLowerCase().contains(busca);

                    // A linha só entra se passar em AMBOS os filtros ao mesmo tempo
                    if (filtroPorta && filtroBusca) {
                        sb.append(" Servidor Principal - ").append(linha).append("\n");
                    }
                }
                textArea.setText(sb.toString());

                // Gerenciamento do Scroll e do Caret

            } catch (IOException e) {
                textArea.setText("Erro ao ler arquivo: " + e.getMessage());
            }
        });
    }

    private void readerLogClient(String host, String user, String password, String remoteFile) {
        System.out.println("Host: " + host + " User: " + user + " Password: " + password + " RemotFile: " + remoteFile);
        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(user, host, 22);
            session.setPassword(password);
            // Ignorar verificação de host key (apenas para redes locais seguras)
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect();
            // Abrir canal de execução
            ChannelExec channel = (ChannelExec) session.openChannel("exec");
            channel.setCommand("cat " + remoteFile);
            InputStream in = channel.getInputStream();
            channel.connect();
            // Lendo o conteúdo do log
            BufferedReader reader = new BufferedReader(new InputStreamReader(in));
            String line;
            System.out.println("--- Início do Log ---");
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
            channel.disconnect();
            session.disconnect();
            System.out.println("--- Conexão Encerrada ---");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void monitorarArquivo(Path caminhoArquivo, JTextArea textArea, JScrollPane scrollPane,
            JComboBox<String> select_porta, JTextField campoBusca, boolean ativado) {
        status_agente = isAgenteRodando();
        int scrollValue = scrollPane.getVerticalScrollBar().getValue();
        try (WatchService watchService = FileSystems.getDefault().newWatchService()) {
            // Path caminho =
            // Paths.get("C:/Users/noslineda/Documents/NetBeansProjects/Agente.log");
            Path caminho = Paths.get("/home/nuc/Agente/Agente.log");
            Path parent = caminhoArquivo.getParent();
            if (parent == null)
                parent = Paths.get(".");
            parent.register(watchService, StandardWatchEventKinds.ENTRY_MODIFY);
            while (true) {
                WatchKey key = watchService.take();

                for (WatchEvent<?> event : key.pollEvents()) {
                    if (event.context().toString().equals(caminhoArquivo.getFileName().toString())) {
                        SwingUtilities.invokeLater(() -> {
                            // Captura os valores ANTES de carregar o novo log
                            JScrollBar vertical = scrollPane.getVerticalScrollBar();
                            int currentScrollValue = vertical.getValue();
                            // Verifica se o usuário está no fim (com uma margem de erro de 10 pixels)
                            boolean isAtBottom = (vertical.getValue()
                                    + vertical.getVisibleAmount()) >= (vertical.getMaximum() + 100);
                            String portaSelecionada = (String) select_porta.getSelectedItem();
                            // Carrega o log
                            carregarLog(caminhoArquivo, textArea, scrollPane, portaSelecionada, campoBusca,
                                    status_agente);

                            // Aguarda o Swing processar o novo tamanho do texto para ajustar o scroll
                            SwingUtilities.invokeLater(() -> {

                            });
                        });
                    }
                }
                if (!key.reset())
                    break;
            }
        } catch (IOException | InterruptedException e) {
            SwingUtilities.invokeLater(() -> textArea.setText("Erro ao monitorar o arquivo: " + e.getMessage()));
        }
    }

    public static boolean isAgenteRodando() {
        try {
            String os = System.getProperty("os.name").toLowerCase();
            Process processo;
            if (os.contains("win")) {
                processo = Runtime.getRuntime().exec("tasklist /FI \"IMAGENAME eq java.exe\"");
            } else {
                // Usa pgrep para buscar processos Java rodando Agente.jar
                String[] cmd = { "/bin/sh", "-c", "ps aux | grep '[A]gente.jar'" };
                processo = Runtime.getRuntime().exec(cmd);
            }
            BufferedReader leitor = new BufferedReader(new InputStreamReader(processo.getInputStream()));
            String linha;
            while ((linha = leitor.readLine()) != null) {
                // Garante que não é a própria linha do grep
                if (linha.toLowerCase().contains("agente.jar") && !linha.toLowerCase().contains("grep")) {
                    return true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    public static void executarShellScript(String caminhoScript) {
        try {
            ProcessBuilder pb = new ProcessBuilder("bash", caminhoScript);
            pb.redirectErrorStream(true);
            Process process = pb.start();

            // Leia a saída para evitar travamento por buffer cheio
            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(process.getInputStream()))) {
                    String linha;
                    while ((linha = reader.readLine()) != null) {
                        System.out.println(linha);
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void finalizarAgente() {
        try {
            // Encontra o PID do Agente.jar e finaliza com kill -9
            String[] cmd = {
                    "/bin/sh",
                    "-c",
                    "sudo ps aux | grep '[A]gente.jar' | awk '{print $2}' | xargs -r sudo kill -9",

            };
            Process process = Runtime.getRuntime().exec(cmd);
            process.waitFor();
            // System.out.println("Agente.jar finalizado (se estava em execução).");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTbusca;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> select_porta;
    private javax.swing.JSpinner sizeFont;
    // End of variables declaration//GEN-END:variables
}
